### ISSUE TITLE
Padding doesn't work in your custom View

### ISSUE THREAD

**Issue by antontidev** [PregOfficial/UI-Toolkit-SafeArea#1]
Setting padding in your SafeAreaManager doesn't worked properly for me. I change your code a little to:
`style.marginLeft = leftTop.x;
 style.marginTop = leftTop.y;
 style.marginRight = rightBottom.x;
 style.marginBottom = rightBottom.y;`
I'm sure that your SafeAreaManger worked, but now it's not working.

**Comment by antontidev** [comment]
Maybe something in UI Toolkit has been changed since you post your solution here.

**Comment by PregOfficial** [comment]
thanks @antontidev 

if you want, you can create a pull-request
